### ISSUE TITLE
Implement Certificate auth in the IBotDeclarationSettings

### ISSUE THREAD

**Issue by MTCMarkFranco** [wictorwilen/express-msteams-host#5]
Do we have a plan to implement Certificate auth in the IBotDeclarationSettings soon?

**Comment by wictorwilen** [comment]
@MTCMarkFranco - this is the first request of it and it would be a great addition. How would you like to see it implemented? And if you do feel like it - feel free to help out adding this feature.

**Comment by MTCMarkFranco** [comment]
just added the pull request with the changes here #6

**Comment by MTCMarkFranco** [comment]
Just circling back here... do you have some time to review the changes?

**Comment by wictorwilen** [comment]
Now, merged with `preview`.
